### ISSUE TITLE
Aruco detection in Hololens

### ISSUE THREAD

**Issue by PranavShevkar** [SMRazaRizvi96/MR-based-drone-controller#5]
In your scripts I can see that you have used QRTracking from MRTK which is basically a library for tracking QR codes. Can you point me to the code where you have implemented aruco tracking. Thanks in advance

**Comment by SMRazaRizvi96** [comment]
I'm using the `aruco_ros` package from PAL RObotics here

https://github.com/behnamasadi/aruco-ros

**Comment by SMRazaRizvi96** [comment]
I'm using the [aruco_ros](https://github.com/behnamasadi/aruco-ros) package from PAL Robotics, for 6DOF Pose Estimation using AruCo markers.
